### ISSUE TITLE
[Feature Request] Turn Off "Got To Top" arrow

### ISSUE THREAD

**Issue by KenLucke** [jneilliii/OctoPrint-FloatingNavbar#12]
Any chance you could implement this, now that we've narrowed down that it's your plugin? :)

https://github.com/OctoPrint/OctoPrint/issues/4010

**Comment by jneilliii** [comment]
Yes, I can make this an optional component when I get some spare time.

**Comment by jneilliii** [comment]
Should be set with the above commit @KenLucke. You can test by using the URL below in Plugin Manager > Get More > ...from URL and clicking Install. Once installed go into settings and set the `Scroll to Top` height to 0 and that should disable it.

```
https://github.com/jneilliii/OctoPrint-FloatingNavbar/archive/rc.zip
```

**Comment by KenLucke** [comment]
Seem to work fine.  Couldn't just make it "On/Off," could you? [grin]  I'm ass/u/ming that the figure is the minimum height the window needs to be scrolled before the arrow becomes active?

**Comment by jneilliii** [comment]
That is correct, so you could technically put in a large number rather than 0 to also have it not show up. I think it makes more sense to be configurable rather than just an on/off that way anyone can adjust based on their own resolution/text scaling, and monitor orientations. Previously I was just using a 10% of height value.

**Comment by KenLucke** [comment]
It works either way, so I am happy... thanks for the quick fix!
